let studentData = [
  { id: 4051, name: "manoj", email: "manoj@gmail.com" },
  { id: 4050, name: "pankaj", email: "p1@gmail.com" },
  { id: 3050, name: "Neeraj1993", email: "neeraj.singh@adequateinfosoft.com" },
  { id: 3049, name: "Sophia", email: "sophia@gmail.com" },
  { id: 3048, name: "Raju Prasad", email: "raju.nsit@gmail.com" },
  {
    id: 3047,
    name: "Ankiish Thapliyal",
    email: "thapliyalankiish958@gmail.com",
  },
  { id: 3046, name: "Aryan Thapliyal", email: "ashithewarrior@gmail.com" },
  { id: 3045, name: "shivam", email: "shivam@gmail.com" },
  { id: 3044, name: "Navya Upadhyay", email: "navya.adequate@gmail.com" },
  { id: 3043, name: "Ritu singh", email: "ritusinghadequate@gmail.com" },
  { id: 3042, name: "faiz", email: "faizadequate@gmail.com" },
  { id: 3041, name: "Martin Wilson", email: "ravencomputer667@gmail.com" },
  { id: 3040, name: "Shweta Singh", email: "amelia.claire.hi@gmail.com" },
  { id: 3039, name: "jagjit", email: "jagjit.singh.adequate.36@gmail.com" },
  { id: 3038, name: "Ashi 123", email: "ashi123@gmail.com" },
  { id: 3037, name: "shivamvermaa4", email: "shivam.vemaa4@gmail.com" },
  { id: 3036, name: "Sophia", email: "n2@gmail.com" },
  { id: 3035, name: "n1", email: "n1@gmail.com" },
  { id: 3034, name: "neha", email: "neha@gmail.com" },
  { id: 3033, name: "sanjay", email: "sanjay@gmail.com" },
  { id: 3032, name: "Akku2", email: "akku2@gmail.com" },
  { id: 3031, name: "Ashish Thapliyal", email: "ashi1@gmail.com" },
  { id: 3030, name: "singh", email: "singh@gmail.com" },
  { id: 3029, name: "Akku Testing", email: "akku1@gmail.com" },
  { id: 3028, name: "Aakankshi Gupta", email: "aakankshi.cuminte@gmail.com" },
  { id: 3026, name: "Manresh Chandra 5", email: "manresh5@gmail.com" },
  { id: 3025, name: "Manresh Chandra 4", email: "manresh4@gmail.com" },
  { id: 3024, name: "Manresh Chandra 3", email: "manresh3@gmail.com" },
  { id: 3023, name: "Manresh Chandra 2", email: "manresh2@gmail.com" },
  { id: 3022, name: "Raju Prasad", email: "raju.prasad@adequateinfosoft.com" },
  { id: 3021, name: "Ashok Patel", email: "ashoktest@gmail.com" },
  { id: 2021, name: "manresh1", email: "manresh1@gmail.com" },
  { id: 2020, name: "Manresh Chandra", email: "manresh@gmail.com" },
  { id: 2019, name: "Test", email: "aakankshi7@gmail.com" },
  { id: 2018, name: "aakankshi6", email: "aakankshi6@gmail.com" },
  { id: 2017, name: "aakankshi5", email: "aakankshi5@gmail.com" },
  { id: 2016, name: "aakankshi4", email: "aakankshi4@gmail.com" },
  { id: 2015, name: "aakankshi3", email: "aakankshi3@gmail.com" },
  { id: 2014, name: "Aakankshi 2", email: "aakankshi2@gmail.com" },
  { id: 2013, name: "Aakankshi 1", email: "aakankshi1@gmail.com" },
  { id: 2012, name: "Aakankshi Gupta", email: "aakankshi@gmail.com" },
  { id: 2011, name: "Aankashi", email: "alokpatel@gmail.com" },
  { id: 2010, name: "Test 10", email: "test02@gmail.com" },
  { id: 2009, name: "Test 9", email: "test10@gmail.com" },
  { id: 2008, name: "Test 8", email: "test3@test.com" },
  { id: 2007, name: "Neeraj Singh", email: "neirajsingh100@gmail.com" },
  {
    id: 2006,
    name: "Hr. Niels Henriksen",
    email: "contact@adequateinfosoft.com",
  },
  { id: 2005, name: "Test 6", email: "pankajadequate@gmail.com" },
  { id: 2004, name: "Test 5", email: "pankajws@gmail.com" },
  { id: 2, name: "rajat Saxena", email: "rajat.nirmal@gmail.com" },
  { id: 3, name: "Pankaj Patel", email: "Pankaj@gmail.com" },
  { id: 1003, name: "Test 2", email: "pankajabc@gmail.com" },
  { id: 1004, name: "Test 2", email: "pankajabcd@gmail.com" },
  { id: 1005, name: "Test 3", email: "test@test.com" },
  { id: 1006, name: "Test 4", email: "test1@test.com" },
];

export default studentData;
